name: redirect_tests
on: workflow_dispatch
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
        - name: Checkout Project
          uses: actions/checkout@v1

        - name: Run apache docker
          run: docker run -dit --name apache -p 80:80 -v "$PWD":/usr/local/apache2/htdocs/ -v "$PWD"/.test/conf/httpd.conf:/usr/local/apache2/conf/httpd.conf httpd:2.4

        - name: Install curl
          run: docker exec -i apache sh -c "apt-get update && apt-get install curl"

        - name: Run tests
          run: docker exec -i apache bash < .test/test.sh
